"""Create user tables

Revision ID: ad2bba1bbe30
Revises: 9cf7cab0670c
Create Date: 2025-02-16 21:20:31.587451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2bba1bbe30'
down_revision: Union[str, None] = '9cf7cab0670c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.user_id'], name='posts_poster_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], name='posts_thread_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', name='posts_pkey')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('ix_posts_thread_id', ['thread_id'], unique=False)
        batch_op.create_index('ix_posts_poster_id', ['poster_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscription_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], name='subscriptions_thread_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('subscription_id', name='subscriptions_pkey')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_subscriptions_thread_id', ['thread_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_of_joining', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_creation', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', name='threads_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### Commands auto-generated by Alembic - adjust as needed ###
    op.drop_index(op.f('ix_subscriptions_thread_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_posts_poster_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_thread_id'), table_name='posts')

    op.drop_table('subscriptions')
    op.drop_table('posts')
    op.drop_table('threads')
    op.drop_table('users')
