"""empty message

Revision ID: e6e92d4e26ae
Revises: 
Create Date: 2025-01-26 19:09:50.156854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf7cab0670c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### Commands auto-generated by Alembic - adjust as needed ###
    op.create_table(
        'users',
        sa.Column('user_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('first_name', sa.String()),
        sa.Column('last_name', sa.String()),
        sa.Column('nickname', sa.String()),
        sa.Column('password', sa.String()),
        sa.Column('email', sa.String(), unique=True),
        sa.Column('date_of_birth', sa.Date())
    )

    op.create_table(
        'threads',
        sa.Column('thread_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String()),
        sa.Column('description', sa.String()),
        sa.Column('date_of_creation', sa.Date())
    )

    op.create_table(
        'posts',
        sa.Column('post_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('thread_id', sa.Integer, sa.ForeignKey('threads.thread_id')),
        sa.Column('poster_id', sa.Integer, sa.ForeignKey('users.user_id')),
        sa.Column('content', sa.String()),
        sa.Column('post_date', sa.Date()),
        sa.Column('rating', sa.Integer(), server_default=sa.text('0'))
    )

    op.create_table(
        'subscriptions',
        sa.Column('subscription_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.user_id')),
        sa.Column('thread_id', sa.Integer, sa.ForeignKey('threads.thread_id')),
        sa.Column('subscription_date', sa.Date())
    )

    # Create indexes for foreign keys marked with index=True
    op.create_index(op.f('ix_posts_thread_id'), 'posts', ['thread_id'], unique=False)
    op.create_index(op.f('ix_posts_poster_id'), 'posts', ['poster_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_thread_id'), 'subscriptions', ['thread_id'], unique=False)
    # ### End Alembic commands ###
def downgrade():
    # ### Commands auto-generated by Alembic - adjust as needed ###
    op.drop_index(op.f('ix_subscriptions_thread_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_posts_poster_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_thread_id'), table_name='posts')

    op.drop_table('subscriptions')
    op.drop_table('posts')
    op.drop_table('threads')
    op.drop_table('users')
